# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MAwLsAOnd80nxcqEFDwz00_mwZYZSVoB
"""

# @title 📊 [멀티 분리] 해외 및 국내 퀀트 데이터 일괄 수집 및 마크다운 생성기 { run: "auto" }
# @markdown ---
# @markdown ### 🌐 해외 시장 설정 (티커 직접 입력, 쉼표로 구분)
해외_종목_목록 = "NVDA, NVDL, GOOGL, META, LEU, MP, ^SOX, MU, XLK, MRVL, TSM, WDC, AVGO, GEV"  # @param {type:"string"}
해외_수집_기간 = "5년"          # @param ["1년", "3년", "5년", "10년"]
해외_자문_기간 = "6개월"        # @param ["1개월", "3개월", "6개월", "1년"]

# @markdown ---
# @markdown ### 🇰🇷 국내 시장 설정 (티커 직접 입력, 쉼표로 구분)
국내_종목_목록 = "000660.KS, 017670.KS, 005930.KS, 032830.KS, 009150.KS, 012330.KS, 005380.KS, 012450.KS, 358570.KS, 042700.KS, 003230.KS"  # @param {type:"string"}
국내_수집_기간 = "5년"          # @param ["1년", "3년", "5년", "10년"]
국내_자문_기간 = "6개월"        # @param ["1개월", "3개월", "6개월", "1년"]
# @markdown ---

import datetime
import os
import numpy as np
import pandas as pd
import requests
import yfinance as yf

def fetch_and_calculate(target_ticker, period_str):
    end_date = datetime.datetime.now()
    period_map = {"1년": 1, "3년": 3, "5년": 5, "10년": 10}
    years = period_map.get(period_str, 5)
    start_date = end_date - datetime.timedelta(days=365 * years)

    print(f"🔄 [{target_ticker}] 최근 {period_str}치 일봉 데이터 다운로드 및 퀀트 연산 중...")
    try:
        df = yf.download(target_ticker, start=start_date, end=end_date, progress=False, auto_adjust=True)
    except Exception:
        return None

    if df is None or df.empty:
        return None

    close_prices = pd.Series(df['Close'].values.flatten(), index=df.index).dropna()

    if len(close_prices) < 30:
        return None

    df_calc = pd.DataFrame(index=df.index)
    df_calc['Close'] = close_prices

    # Envelope (25, 15, 15)
    ma25 = close_prices.rolling(window=25).mean()
    df_calc['Env_Upper'] = ma25 * 1.15
    df_calc['Env_Lower'] = ma25 * 0.85

    # MACD (12, 26, 9)
    exp1 = close_prices.ewm(span=12, adjust=False).mean()
    exp2 = close_prices.ewm(span=26, adjust=False).mean()
    df_calc['MACD'] = exp1 - exp2
    df_calc['Signal'] = df_calc['MACD'].ewm(span=9, adjust=False).mean()

    # RSI (18)
    delta = close_prices.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.ewm(alpha=1/18, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1/18, adjust=False).mean()
    rs = avg_gain / (avg_loss + 1e-9)
    df_calc['RSI'] = 100 - (100 / (1 + rs))

    return df_calc

def fetch_macro_indicators():
    vix_df = yf.download("^VIX", period="5d", progress=False, auto_adjust=True)
    vix_val = float(vix_df['Close'].values.flatten()[-1]) if not vix_df.empty else 15.0

    fear_greed_val = 50.0
    try:
        url = "https://production.dataviz.cnn.io/index/fearandgreed/graphdata"
        headers = {'User-Agent': 'Mozilla/5.0'}
        res = requests.get(url, headers=headers, timeout=5)
        if res.status_code == 200:
            data = res.json()
            fear_greed_val = float(data['fear_and_greed']['score'])
    except Exception:
        pass

    return vix_val, fear_greed_val

def generate_market_report(ticker_string, period_str, advice_str, market_title, file_name, vix, fear_greed):
    tickers = [t.strip().upper() for t in ticker_string.split(",") if t.strip()]

    report_content = f"""# 🤖 [AI {market_title} 퀀트 분석 데이터 패키지]

당신은 20년 경력의 베테랑 퀀트 투자 분석가입니다. 주관적 추측이나 감정적 판단을 완전히 배제하고, 오직 아래 실시간 수집 데이터와 기술적 지표만을 절대적인 근거로 삼아 객관적인 분석을 수행합니다.

## [공통 거시 환경 지표]
- 글로벌 변동성 VIX 지수: {vix:.2f}
- CNN 공포탐욕지수: {fear_greed:.1f}
- 데이터 수집 기준 기간: 최근 {period_str}
- AI 집중 자문 기간: 최근 {advice_str}

---
"""
    success_count = 0
    for ticker in tickers:
        df_full = fetch_and_calculate(ticker, period_str)

        if df_full is None or df_full.empty:
            print(f"⚠️ [{ticker}] 데이터를 불러오지 못해 건너뜁니다.")
            continue

        last_row = df_full.iloc[-1]
        current_price = float(last_row['Close'])
        env_upper = float(last_row['Env_Upper'])
        env_lower = float(last_row['Env_Lower'])
        macd = float(last_row['MACD'])
        signal = float(last_row['Signal'])
        rsi = float(last_row['RSI'])

        env_status = "과열(고점 위험)" if current_price >= env_upper else ("과매도(저점 기회)" if current_price <= env_lower else "정상")
        macd_cross = "골든크로스" if macd > signal else "데드크로스"

        stock_section = f"""
## 📌 종목 티커: {ticker}

**📊 [Python 연산 및 수집 데이터 결과]**
- 현재 주가: {current_price:,.2f}
- VIX 지수 / 공포탐욕지수: VIX {vix:.2f} / 공포탐욕 {fear_greed:.1f}
- Envelope (25, 15, 15): 상한선 {env_upper:,.2f} / 하한선 {env_lower:,.2f} / 현재 위치: {env_status}
- MACD (12, 26, 9): MACD {macd:.4f} / 시그널 {signal:.4f} / 교차 상태: {macd_cross}
- RSI (18): {rsi:.2f}

**🔍 [지표별 심층 진단]**
- Envelope (25, 15, 15): [정상 / 과열(고점 위험) / 과매도(저점 기회) 중 택1] - (현재가 {current_price:,.2f}와 상하한선 수치를 바탕으로 한 구체적인 판단 근거 1~2줄 작성)
- MACD (12, 26, 9): [정상 / 과열(고점 위험) / 과매도(저점 기회) 중 택1] - (MACD {macd:.4f}와 시그널 {signal:.4f}의 위치 및 교차 상태를 반영한 구체적인 근거 1~2줄 작성)
- RSI (18): [정상 / 과열(고점 위험) / 과매도(저점 기회) 중 택1] - (RSI {rsi:.2f} 수치가 의미하는 모멘텀 과열/침체 여부에 대한 구체적인 근거 1~2줄 작성)

**💡 [최종 결론 및 투자 자문]**
최근 {period_str}의 장기 추세와 {advice_str}의 모멘텀, 그리고 거시 지표를 종합하여 **[매수 (Buy) / HOLD (보유) / 매도 (Sell)]** 중 하나를 명확히 선언하고, 그 타당한 이유를 3~4문장의 전문적이고 설득력 있는 문장으로 상세히 서술할 것.

---
"""
        report_content += stock_section
        success_count += 1

    if success_count > 0:
        with open(file_name, "w", encoding="utf-8") as f:
            f.write(report_content)
        print(f"✅ [{market_title}] 총 {success_count}개 종목 파일 생성 완료: '{file_name}'")
    else:
        print(f"❌ [{market_title}] 유효하게 수집된 종목 데이터가 없습니다.")

try:
    vix, fear_greed = fetch_macro_indicators()

    print("--- 🌍 해외 시장 데이터 수집 시작 ---")
    generate_market_report(해외_종목_목록, 해외_수집_기간, 해외_자문_기간, "해외 시장", "quant_overseas_report.md", vix, fear_greed)

    print("\n--- 🇰🇷 국내 시장 데이터 수집 시작 ---")
    generate_market_report(국내_종목_목록, 국내_수집_기간, 국내_자문_기간, "국내 시장", "quant_domestic_report.md", vix, fear_greed)

    print("\n💡 생성된 파일들(`quant_overseas_report.md`, `quant_domestic_report.md`)을 각각 제미나이 채팅창에 업로드하고 분석을 요청하세요!")

except Exception as e:
    print(f"❌ 실행 중 오류 발생: {e}")